services:
  nachet-detector:
    # build:
    #   context: ./nachet-model/AzureMLSeedDet
    #   dockerfile: Dockerfile
    container_name: nachet-detector
    image: ghcr.io/ai-cfia/nachet-backend:29-azureml-seed-detector
    command: "./startup.sh && bash -c 'azmlinfsrv --entry_script /app/scoring_file_v_1_0_0.py'"
    ports:
      - "12380:5001"
      - "12381:8883"
      - "12382:8888"
    # network_mode: bridge
    # networks:
    #   - nachet-network
