services:

  pytorchgpu:
    build: 
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        project: ../../
    image: pytorch-gpu-24
    restart: unless-stopped
    container_name: pytorch-gpu-24
    env_file:
      - .env
    volumes: 
      - ../../:/project
    # ports:
    #   - '8888:8888'
    shm_size: '1gb'
    ulimits:
      stack: 67108864
      memlock: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
