services:

  pytorchgpu:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ai-cfia/nachet-model-ccds/pytorch-gpu-24-devenv:2025031401
    restart: no
    container_name: pytorch-gpu-24
    env_file:
      - .env
    volumes: 
      - ../../:/project
      # - /tmp:/tmp
    # ports:
    #   - '8888:8888'
    shm_size: '1gb'
    ulimits:
      stack: 67108864
      memlock: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
